# Makefile Stackoverflow CV

SHELL := /bin/bash
FILENAME := $(shell which pdflatex)

.PHONY: help # print this help list
help:
	grep PHONY Makefile | sed 's/.PHONY: /make /' | grep -v grep

.PHONY: test # test if you are ready to make your CV
test:
ifneq (,$(wildcard ${FILENAME}))
	@echo You are ready to make your CV
else
#	@echo You have to install pdflatex
#	@echo Example for debian / ubuntu: apt-get install pdflatex texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
	@echo You have to install required packages
	@echo Run the following command:
	@echo sudo dnf install \
        texlive-scheme-medium \
        texlive-collection-latexextra \
        texlive-collection-fontsextra \
        texlive-roboto \
        texlive-fontawesome5 \
        texlive-tcolorbox \
        texlive-geometry \
        texlive-moresize \
        texlive-xetex \
        texlive-luatex
endif

.PHONY: clean # clean all support files generated by pdflatex
clean:
	@rm -f *.aux *.dvi *.log *.out *.bak
	@echo "Clean done.";

.PHONY: cv # generate the new PDF file
cv:
	@echo "Building PDF file .... $^"
	@xelatex stackoverflow.tex
	@echo "CV Done! Look for file named stackoverflow.pdf"

.PHONY: all # generate the new PDF file and clean all support files generated by pdflatex
all: cv
	make clean

.PHONY: upgrade # generate the new PDF file with the upgraded version
upgrade:
	@echo "Building PDF file with the upgraded version .... $^"
	@xelatex stackoverflow-upgraded-version.tex
	@echo "CV Done! Look for file named stackoverflow-upgraded-version.pdf"

.PHONY: graphed # generate the new PDF file with the upgraded version
graphed:
	@echo "Building PDF file with the upgraded version .... $^"
	@xelatex stackoverflow-graphed-version.tex
	@echo "CV Done! Look for file named stackoverflow-graphed-version.pdf"
